version: '3.7'
networks:
  nginx-proxy:
    external: true
  internal:
    external: false
services:
  plex:
    image: plexinc/pms-docker:latest
    container_name: plex
    volumes:
      - ./config/plexdata/config:/config
      - ./config/transcode:/transcode
      - $MEDIADIR/tv:/tv
      - $MEDIADIR/movies:/movies
      - $MEDIADIR/education:/education
      - $MEDIADIR/audiobooks:/audiobooks
    networks:
      - internal
    ports:
      - "32400:32400/tcp"
      - "3005:3005/tcp"
      - "8324:8324/tcp"
      - "32469:32469/tcp"
      - "1900:1900/udp"
      - "32410:32410/udp"
      - "32412-32414:32412-32414/udp"
      - "5353:5353/udp"
    environment:
      - TZ=$TZ
      - PLEX_UID=$PUID
      - PLEX_GID=$PGID
      - VERSION=latest
      - $ADVERTISEIP
    restart: unless-stopped
    pull_policy: always
  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config/radarr:/config
      - $MEDIADIR/movies:/movies
      - $MEDIADIR/downloads:/downloads
    networks:
      - internal
    ports:
      - 7878:7878
    environment:
      - TZ=$TZ
      - PUID=$PUID
      - PGID=$PGID
    restart: unless-stopped
    pull_policy: always
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config/sonarr:/config
      - $MEDIADIR/tv:/tv
      - $MEDIADIR/downloads:/downloads
    networks:
      - internal
    ports:
      - 8989:8989
    environment:
      - TZ=$TZ
      - PUID=$PUID
      - PGID=$PGID
    restart: unless-stopped
    pull_policy: always
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - TZ=$TZ
      - PUID=$PUID
      - PGID=$PGID
    volumes:
      - ./config/bazarr:/config
      - $MEDIADIR/movies:/movies
      - $MEDIADIR/tv:/tv
    ports:
      - 6767:6767
    restart: unless-stopped
    pull_policy: always
  nzbget:
    image: linuxserver/nzbget:latest
    container_name: nzbget
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config/nzbget:/config
      - $MEDIADIR/downloads:/downloads
    networks:
      - internal
    ports:
      - 6789:6789
    environment:
      - TZ=$TZ
      - PUID=$PUID
      - PGID=$PGID
    restart: unless-stopped
    pull_policy: always
  organizr:
    image: organizr/organizr:latest
    container_name: organizr
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config/organizr:/config
    networks:
      - internal
    ports:
      - 8080:80
    environment:
      - TZ=$TZ
      - PUID=$PUID
      - PGID=$PGID
    restart: unless-stopped
    pull_policy: always
  overseerr:
    image: lscr.io/linuxserver/overseerr
    container_name: overseerr
    networks:
      - nginx-proxy
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - VIRTUAL_HOST=$PUBLICHOSTNAME
      - LETSENCRYPT_HOST=$PUBLICHOSTNAME
    volumes:
      - ./config/overseerr:/config
    restart: unless-stopped
    pull_policy: always
  tautulli:
    image: linuxserver/tautulli:latest
    container_name: tautulli
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config/tautulli:/config
      - ./config/plexdata/config/Library/Application Support/Plex Media Server/Logs:/logs:ro
    networks:
      - nginx-proxy
    environment:
      - TZ=$TZ
      - PUID=$PUID
      - PGID=$PGID
      - VIRTUAL_HOST=history.$PUBLICHOSTNAME
      - LETSENCRYPT_HOST=history.$PUBLICHOSTNAME
    restart: unless-stopped
    pull_policy: always
  ddclient:
    image: linuxserver/ddclient:latest
    container_name: ddclient
    networks:
      - internal
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - ./config/ddclient:/config
    restart: unless-stopped
    pull_policy: always
